---@meta

---@class TargetedSpells
---@field IsMidnight boolean
---@field EventRegistry CallbackRegistryMixin
---@field Events table<string, string>
---@field Enum TargetedSpellsEnums
---@field Settings TargetedSpellsSettings
---@field LoginFnQueue table<string, function>

---@class TargetedSpellsEnums

---@class SliderSettings
---@field min number
---@field max number
---@field step number

---@class TargetedSpellsSettings
---@field CreateSettings fun()
---@field Keys table<'Self' | 'Party', table<string, string>>
---@field GetSelfDefaultSettings fun(): SavedVariablesSettingsSelf
---@field GetPartyDefaultSettings fun(): SavedVariablesSettingsParty
---@field GetSliderSettingsForOption fun(key: string): SliderSettings

---@class SavedVariables
---@field Settings SavedVariablesSettings

---@class SavedVariablesSettings
---@field Self SavedVariablesSettingsSelf
---@field Party SavedVariablesSettingsParty

---@class SavedVariablesSettingsSelf
---@field Enabled boolean
---@field Width number
---@field Height number
---@field Gap number
---@field Direction Direction
---@field LoadConditionContentType boolean[]
---@field LoadConditionRole boolean[]
---@field PlaySound boolean
---@field Sound string
---@field LoadConditionSoundContentType boolean[]
---@field SortOrder SortOrder
---@field Grow Grow

---@class SavedVariablesSettingsParty
---@field Enabled boolean
---@field Width number
---@field Height number
---@field Gap number
---@field Direction Direction
---@field LoadConditionContentType boolean[]
---@field LoadConditionRole boolean[]
---@field OffsetX number
---@field OffsetY number
---@field SourceAnchor Anchor
---@field TargetAnchor Anchor
---@field SortOrder SortOrder
---@field Grow Grow

---@class TargetedSpellsSelfPreviewFrame: Frame
---@field GetChildren fun(self: TargetedSpellsSelfPreviewFrame): TargetedSpellsMixin

---@class TargetedSpellsMixin : Frame
---@field Overlay Texture
---@field Icon Texture
---@field Cooldown Cooldown
---@field OnLoad fun(self: TargetedSpellsMixin)
---@field kind string<'Party' | 'Self'>
---@field SetKind fun(self: TargetedSpellsMixin, kind: string)
---@field GetKind fun(self: TargetedSpellsMixin): string
---@field OnKindChanged fun(self: TargetedSpellsMixin, kind: string)
---@field unit string?
---@field SetUnit fun(self: TargetedSpellsMixin, unit: string)
---@field GetUnit fun(self: TargetedSpellsMixin): string
---@field startTime number?
---@field ClearStartTime fun(self: TargetedSpellsMixin)
---@field GetStartTime fun(self: TargetedSpellsMixin): number
---@field SetStartTime fun(self: TargetedSpellsMixin)
---@field castTime number?
---@field GetCastTime fun(self: TargetedSpellsMixin): number
---@field SetCastTime fun(self: TargetedSpellsMixin, castTime: number)
---@field texture number?
---@field SetSpellTexture fun(self: TargetedSpellsMixin, texture: number?)
---@field GetSpellTexture fun(self: TargetedSpellsMixin)
---@field RefreshSpellTexture fun(self: TargetedSpellsMixin)
---@field RefreshSpellCooldownInfo fun(self: TargetedSpellsMixin)
---@field hideTimer FunctionContainer?
---@field loopTicker FunctionContainer?
---@field OnSizeChanged fun(self: TargetedSpellsMixin, width: number, height: number)
---@field OnSettingChanged fun(self: TargetedSpellsMixin, key: string, value: number|string)
---@field UpdateShownState fun(self: TargetedSpellsMixin)
---@field ShouldBeShown fun(self: TargetedSpellsMixin): boolean
---@field Reposition fun(self: TargetedSpellsMixin, point: string, relativeTo: Frame, relativePoint: string, offsetX: number, offsetY: number)
---@field StartPreviewLoop fun(self: TargetedSpellsMixin, RepositionPreviewFrames: fun())
---@field StopPreviewLoop fun(self: TargetedSpellsMixin)
---@field settingsCallbackId number?

---@class IconDataProviderMixin
---@field GetRandomIcon fun(self: IconDataProviderMixin): number

---@class FramePool
---@field Acquire fun(self: FramePool): TargetedSpellsMixin
---@field Release fun(self: FramePool, frame: TargetedSpellsMixin)

---@class TargetedSpellsSelfEditModeFrame : Frame
---@field maxFrameCount number
---@field demoPlaying boolean
---@field frames TargetedSpellsMixin[]
---@field buildingFrames true|nil
---@field OnLoad fun(self: TargetedSpellsSelfEditModeFrame)
---@field RepositionPreviewFrames fun(self: TargetedSpellsSelfEditModeFrame)
---@field AcquireFrame fun(self: TargetedSpellsSelfEditModeFrame): TargetedSpellsMixin
---@field ReleaseFrame fun(self: TargetedSpellsSelfEditModeFrame, frame: TargetedSpellsMixin)
---@field StartDemo fun(self: TargetedSpellsSelfEditModeFrame)
---@field EndDemo fun(self: TargetedSpellsSelfEditModeFrame, forceDisable: boolean?)
---@field demoTimers { tickers: table<number, FunctionContainer>, timers: table<number, FunctionContainer> }
---@field LoopFrame fun(self: TargetedSpellsSelfEditModeFrame, frame: TargetedSpellsMixin, index: number)
---@field framePool FramePool
---@field OnSettingsChanged fun(self: TargetedSpellsSelfEditModeFrame, key: string, value: number|string)
---@field OnEditModePositionChanged fun(self: TargetedSpellsSelfEditModeFrame, frame: Frame, layoutName: string, point: string, x: number, y: number)
---@field ResizeSelf fun(self: TargetedSpellsSelfEditModeFrame)

---@class TargetedSpellsPartyEditModeFrame : Frame
---@field demoPlaying boolean
---@field maxUnitCount number
---@field useRaidStylePartyFrames boolean
---@field amountOfPreviewFramesPerUnit number
---@field framePool FramePool
---@field frames table<number, TargetedSpellsMixin[]>
---@field buildingFrames true|nil
---@field OnLoad fun(self: TargetedSpellsPartyEditModeFrame)
---@field RepositionPreviewFrames fun(self: TargetedSpellsPartyEditModeFrame)
---@field RepositionSelf fun(self: TargetedSpellsPartyEditModeFrame)
---@field OnSettingsChanged fun(self: TargetedSpellsPartyEditModeFrame, key: string, value: number|string)
---@field OnEditModePositionChanged fun(self: TargetedSpellsPartyEditModeFrame, frame: Frame, layoutName: string, point: string, x: number, y: number)
---@field AcquireFrame fun(self: TargetedSpellsPartyEditModeFrame): TargetedSpellsMixin
---@field ReleaseFrame fun(self: TargetedSpellsPartyEditModeFrame, frame: TargetedSpellsMixin)
---@field StartDemo fun(self: TargetedSpellsPartyEditModeFrame)
---@field EndDemo fun(self: TargetedSpellsPartyEditModeFrame, forceDisable: boolean?)
---@field demoTimers { tickers: table<number, FunctionContainer>, timers: table<number, FunctionContainer> }
---@field LoopFrame fun(self: TargetedSpellsPartyEditModeFrame, frame: TargetedSpellsMixin, index: number)
